version: '3.8'

services:
  migrate:
    build: 
      context: ./docker/migrate
    volumes:
      - ${DB_MIGRATIONS}:/migrations
      - ${DB_DIR}:/db
    entrypoint: ["migrate", "-path=/migrations/", "-database", "sqlite3:///${DB_PATH}"]
    profiles:
      - job
  
  migratepg:
    build: 
      context: ./docker/migrate/release
    volumes:
      - ${DB_MIGRATIONS}:/migrations
      - ${DB_DIR}:/db
    entrypoint: ["migrate", "-path=/migrations/", "-database", "postgres://${PG_USERNAME}:${PG_PASSWORD}@postgresql:5432/${PG_DBNAME}?sslmode=disable"]
    profiles:
      - job

  postgresql:
    image: docker.io/bitnami/postgresql:16
    # ports:
    #   - '5432:5432'
    volumes:
      - ./tmp/data/postgresql:/bitnami/postgresql
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=${PG_USERNAME}
      - POSTGRESQL_PASSWORD=${PG_PASSWORD}
      - POSTGRESQL_URL=${PG_URL}